### PR TITLE
Api.ai Webhook integration

### PR DESCRIPTION
**Pull request by edoardo849**
This package provides integration in apex for the voice recognition and TTS service [api.ai](https://docs.api.ai/docs/webhook). Useful when used with AWS Gateway.

### CODE REVIEW

**Comment by tj** [comment]
nice! I wonder if we're maybe best keeping it to aws-only stuff in here at least, and linking to others. Not a huge deal really but if someone sends another PR for it I'll have no clue if it's valid or not

**Comment by edoardo849** [comment]
Sure! I've sent the PR because of the Slack implementation but I guess I could host this on my Github, no problem.

**Comment by tj** [comment]
Ah true haha I happen to know the Slack one, but we should have done the same there. It would be great to link to any third-party stuff though!

**Comment by tj** [comment]
actually whatever, probably won't be a huge deal in practice, we'll see haha

**Comment by edoardo849** [comment]
ahah, I was about to click on close but you were faster ;-) anyway, let me know if it's an issue I can do a PR on the README with link to my repo. In any case if any PR on this occurs I will definitely help since this comes from a work-related development

**Pull request merged**
